apiVersion: v1
kind: Service
metadata:
  name: service-admin
  namespace: hotel
spec:
  type: NodePort
  selector:
    app: hotel-admin
  ports:
    - protocol: http
      port: 80
      targetPort: 80
      nodePort: 30056
